### ISSUE TITLE
Release a new version (0.3.0 perhaps?)

### ISSUE THREAD

**Issue by jcoyne** [no-reply/linked_vocabs#8]

**Comment by jcoyne** [comment]
This is still a good idea.

**Comment by no-reply** [comment]
:+1: I'll cut a release, then move this to Labs. I can give you co-ownership of the rubygems.

This might have to wait an hour or so; currently in a meeting.

**Comment by jcoyne** [comment]
@no-reply :ok_hand:

**Comment by jcoyne** [comment]
@no-reply we discussed moving this to projecthydra-labs on the tech call. Go ahead when ready.

**Comment by no-reply** [comment]
Release is done. Moving the repo to labs now.

**Comment by no-reply** [comment]
This is moved and Labs owners should have full access. I added @jcoyne as an owner on rubygems. I'm happy to keep merging PRs and helping with RDF.rb & AT compatability, but encourage others to take ownership of development. :)
